name: ecommerce_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1
  get: ^3.22.1
  google_sign_in: ^4.5.6
  firebase_core: "0.5.3"
  firebase_auth: "^0.18.4"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

